export const pageLoaders = {
  auth: () => import("@/pages/Auth"),
  dashboard: () => import("@/pages/Dashboard"),
  calidad: () => import("@/pages/CalidadJornada"),
  calidadImportacion: () => import("@/pages/CalidadImportacion"),
  calidadImportacionControl: () => import("@/pages/CalidadImportacionControl"),
  partesList: () => import("@/pages/PartesList"),
  partDetail: () => import("@/pages/PartDetail"),
  consumoCostes: () => import("@/pages/ConsumoCostes"),
  asistencia: () => import("@/pages/Asistencia"),
  asistenciaComparativa: () => import("@/pages/AsistenciaComparativa"),
  notFound: () => import("@/pages/NotFound"),
  productores: () => import("@/pages/Productores"),
  analisisDiario: () => import("@/pages/AnalisisDiario"),
  ventasCategoriaSegunda: () => import("@/pages/VentasCategoriaSegunda"),
  ventasCategoriaPrimera: () => import("@/pages/VentasCategoriaPrimera"),
  mercadona: () => import("@/pages/Mercadona"),
  // Edeka desconectada temporalmente (jul 2026): la pagina y el hook siguen en
  // el repo (src/pages/Edeka.tsx, src/hooks/useEdeka.ts) para reengancharla.
  cmr: () => import("@/pages/CmrHojasRuta"),
  rrhhDashboard: () => import("@/pages/RrhhDashboard"),
  rrhhPersonas: () => import("@/pages/RrhhPersonas"),
  rrhhAusencias: () => import("@/pages/RrhhAusencias"),
  rrhhAmonestaciones: () => import("@/pages/RrhhAmonestaciones"),
  rrhhVacaciones: () => import("@/pages/RrhhVacaciones"),
  rrhhNominas: () => import("@/pages/RrhhNominas"),
  rrhhComunicaciones: () => import("@/pages/RrhhComunicaciones"),
  comercialDashboard: () => import("@/pages/ComercialDashboard"),
  direccionDashboard: () => import("@/pages/DireccionDashboard"),
  mercadonaProduccion: () => import("@/pages/MercadonaProduccion"),
  ventasMensualImport: () => import("@/pages/VentasMensualImport"),
  economicoPanel: () => import("@/pages/EconomicoPanel"),
  economicoRentabilidad: () => import("@/pages/EconomicoRentabilidad"),
  economicoCmv: () => import("@/pages/EconomicoCmv"),
  economicoProductos: () => import("@/pages/EconomicoProductos"),
  economicoFacturacion: () => import("@/pages/EconomicoFacturacion"),
  economicoCostes: () => import("@/pages/EconomicoCostes"),
  economicoFruta: () => import("@/pages/EconomicoFruta"),
  economicoPrecios: () => import("@/pages/EconomicoPrecios"),
  comunicacionesCampo: () => import("@/pages/ComunicacionesCampo"),
  mapa: () => import("@/pages/MapaHerramienta"),
  entradas: () => import("@/pages/EntradasBascula"),
  trazabilidad: () => import("@/pages/TrazabilidadLote"),
  calibrador: () => import("@/pages/Calibrador"),
  limpiezaBox: () => import("@/pages/LimpiezaBox"),
  stockConsumibles: () => import("@/pages/StockConsumibles"),
  historicoImport: () => import("@/pages/HistoricoImport"),
  importarBandeja: () => import("@/pages/ImportarBandeja"),
  // ─── Rediseño 13-08-2026: páginas que alojan varias vistas en pestañas ───
  // Cada una monta las páginas de arriba tal cual (ver PaginaConVistas), así
  // que el precargado apunta al contenedor y las vistas se cargan al abrirse.
  analisisPorProductor: () => import("@/pages/AnalisisPorProductor"),
  economicoCostesPanel: () => import("@/pages/EconomicoCostesPanel"),
  rrhhPlantilla: () => import("@/pages/RrhhPlantilla"),
  rrhhAsistencia: () => import("@/pages/RrhhAsistencia"),
  comercialVentasCategoria: () => import("@/pages/ComercialVentasCategoria"),
  datosImportar: () => import("@/pages/DatosImportar"),
  datosFuentes: () => import("@/pages/DatosFuentes"),
};

const preloadByPath: Record<string, () => Promise<unknown>> = {
  "/produccion": pageLoaders.dashboard,
  "/mapa": pageLoaders.mapa,
  "/entradas": pageLoaders.entradas,
  "/trazabilidad": pageLoaders.trazabilidad,
  "/calibrador": pageLoaders.analisisPorProductor,
  "/calidad": pageLoaders.calidad,
  "/calidad/importacion": pageLoaders.calidadImportacion,
  "/partes": pageLoaders.partesList,
  "/costes/consumos": pageLoaders.economicoCostesPanel,
  "/limpieza": pageLoaders.limpiezaBox,
  "/consumibles": pageLoaders.stockConsumibles,
  "/historico": pageLoaders.datosImportar,
  "/importar": pageLoaders.datosImportar,
  "/datos/fuentes": pageLoaders.datosFuentes,
  "/costes/asistencia": pageLoaders.rrhhAsistencia,
  "/costes/asistencia/comparativa": pageLoaders.rrhhAsistencia,
  "/productores": pageLoaders.analisisPorProductor,
  "/analisis/diario": pageLoaders.analisisDiario,
  "/ventas/categoria-segunda": pageLoaders.comercialVentasCategoria,
  "/ventas/categoria-primera": pageLoaders.comercialVentasCategoria,
  "/mercadona": pageLoaders.mercadonaProduccion,
  "/comercial": pageLoaders.comercialDashboard,
  "/comercial/ventas-mes": pageLoaders.comercialVentasCategoria,
  "/direccion": pageLoaders.direccionDashboard,
  "/comercial/mercadona": pageLoaders.mercadona,
  "/rrhh/mercadona": pageLoaders.mercadona,
  "/cmr": pageLoaders.cmr,
  "/rrhh": pageLoaders.rrhhDashboard,
  "/rrhh/personas": pageLoaders.rrhhPlantilla,
  "/rrhh/ausencias": pageLoaders.rrhhPlantilla,
  "/rrhh/amonestaciones": pageLoaders.rrhhPlantilla,
  "/rrhh/vacaciones": pageLoaders.rrhhPlantilla,
  "/rrhh/nominas": pageLoaders.rrhhNominas,
  "/rrhh/comunicaciones": pageLoaders.rrhhPlantilla,
  "/campo/comunicaciones": pageLoaders.comunicacionesCampo,
  "/economico": pageLoaders.economicoPanel,
  "/economico/rentabilidad": pageLoaders.economicoRentabilidad,
  "/economico/cmv": pageLoaders.economicoCostesPanel,
  "/economico/productos": pageLoaders.economicoCostesPanel,
  "/economico/facturacion": pageLoaders.economicoFacturacion,
  "/economico/costes": pageLoaders.economicoCostesPanel,
  "/economico/fruta": pageLoaders.economicoCostesPanel,
  "/economico/precios": pageLoaders.economicoPrecios,
};

export function preloadRoute(path: string) {
  const loader =
    preloadByPath[path] ??
    (path.startsWith("/partes/")
      ? pageLoaders.partDetail
      : path.startsWith("/calidad/importacion/")
        ? pageLoaders.calidadImportacionControl
        : null);
  if (loader) void loader();
}
