export const pageLoaders = {
  auth: () => import("@/pages/Auth"),
  dashboard: () => import("@/pages/Dashboard"),
  calidad: () => import("@/pages/CalidadJornada"),
  partesList: () => import("@/pages/PartesList"),
  partDetail: () => import("@/pages/PartDetail"),
  consumoCostes: () => import("@/pages/ConsumoCostes"),
  asistencia: () => import("@/pages/Asistencia"),
  asistenciaComparativa: () => import("@/pages/AsistenciaComparativa"),
  notFound: () => import("@/pages/NotFound"),
  productores: () => import("@/pages/Productores"),
  analisisDiario: () => import("@/pages/AnalisisDiario"),
  ventasCategoriaSegunda: () => import("@/pages/VentasCategoriaSegunda"),
  ventasCategoriaPrimera: () => import("@/pages/VentasCategoriaPrimera"),
  mercadona: () => import("@/pages/Mercadona"),
  // Edeka desconectada temporalmente (jul 2026): la pagina y el hook siguen en
  // el repo (src/pages/Edeka.tsx, src/hooks/useEdeka.ts) para reengancharla.
  cmr: () => import("@/pages/CmrHojasRuta"),
  rrhhDashboard: () => import("@/pages/RrhhDashboard"),
  rrhhPersonas: () => import("@/pages/RrhhPersonas"),
  rrhhAusencias: () => import("@/pages/RrhhAusencias"),
  rrhhAmonestaciones: () => import("@/pages/RrhhAmonestaciones"),
  rrhhVacaciones: () => import("@/pages/RrhhVacaciones"),
  rrhhNominas: () => import("@/pages/RrhhNominas"),
  rrhhComunicaciones: () => import("@/pages/RrhhComunicaciones"),
  comercialDashboard: () => import("@/pages/ComercialDashboard"),
  direccionDashboard: () => import("@/pages/DireccionDashboard"),
  mercadonaProduccion: () => import("@/pages/MercadonaProduccion"),
  ventasMensualImport: () => import("@/pages/VentasMensualImport"),
  economicoPanel: () => import("@/pages/EconomicoPanel"),
  economicoCmv: () => import("@/pages/EconomicoCmv"),
  economicoFacturacion: () => import("@/pages/EconomicoFacturacion"),
  economicoCostes: () => import("@/pages/EconomicoCostes"),
  economicoFruta: () => import("@/pages/EconomicoFruta"),
  economicoPrecios: () => import("@/pages/EconomicoPrecios"),
  comunicacionesCampo: () => import("@/pages/ComunicacionesCampo"),
  mapa: () => import("@/pages/MapaHerramienta"),
  entradas: () => import("@/pages/EntradasBascula"),
  trazabilidad: () => import("@/pages/TrazabilidadLote"),
  limpiezaBox: () => import("@/pages/LimpiezaBox"),
  historicoImport: () => import("@/pages/HistoricoImport"),
};

const preloadByPath: Record<string, () => Promise<unknown>> = {
  "/produccion": pageLoaders.dashboard,
  "/mapa": pageLoaders.mapa,
  "/entradas": pageLoaders.entradas,
  "/trazabilidad": pageLoaders.trazabilidad,
  "/calidad": pageLoaders.calidad,
  "/partes": pageLoaders.partesList,
  "/costes/consumos": pageLoaders.consumoCostes,
  "/limpieza": pageLoaders.limpiezaBox,
  "/historico": pageLoaders.historicoImport,
  "/costes/asistencia": pageLoaders.asistencia,
  "/costes/asistencia/comparativa": pageLoaders.asistenciaComparativa,
  "/productores": pageLoaders.productores,
  "/analisis/diario": pageLoaders.analisisDiario,
  "/ventas/categoria-segunda": pageLoaders.ventasCategoriaSegunda,
  "/ventas/categoria-primera": pageLoaders.ventasCategoriaPrimera,
  "/mercadona": pageLoaders.mercadonaProduccion,
  "/comercial": pageLoaders.comercialDashboard,
  "/comercial/ventas-mes": pageLoaders.ventasMensualImport,
  "/direccion": pageLoaders.direccionDashboard,
  "/comercial/mercadona": pageLoaders.mercadona,
  "/rrhh/mercadona": pageLoaders.mercadona,
  "/cmr": pageLoaders.cmr,
  "/rrhh": pageLoaders.rrhhDashboard,
  "/rrhh/personas": pageLoaders.rrhhPersonas,
  "/rrhh/ausencias": pageLoaders.rrhhAusencias,
  "/rrhh/amonestaciones": pageLoaders.rrhhAmonestaciones,
  "/rrhh/vacaciones": pageLoaders.rrhhVacaciones,
  "/rrhh/nominas": pageLoaders.rrhhNominas,
  "/rrhh/comunicaciones": pageLoaders.rrhhComunicaciones,
  "/campo/comunicaciones": pageLoaders.comunicacionesCampo,
  "/economico": pageLoaders.economicoPanel,
  "/economico/cmv": pageLoaders.economicoCmv,
  "/economico/facturacion": pageLoaders.economicoFacturacion,
  "/economico/costes": pageLoaders.economicoCostes,
  "/economico/fruta": pageLoaders.economicoFruta,
  "/economico/precios": pageLoaders.economicoPrecios,
};

export function preloadRoute(path: string) {
  const loader = preloadByPath[path] ?? (path.startsWith("/partes/") ? pageLoaders.partDetail : null);
  if (loader) void loader();
}
