-- Enlaces consumible ↔ artículo del ERP curados a mano el 09-09-2026:
-- cruce por nombre validado por PRECIO contra el seed del 01-09 (que salía
-- de facturas reales). Lo que no está aquí quedó SIN enlazar a propósito:
-- cajas EPS/IFCO de alquiler (nuestro precio suma alquiler+lavado, el del
-- ERP es un componente), cantoneras y corbatas de cartón (sin alta en
-- compras del ERP), papel seda de marcas sin artículo, CHEP/Europalet, etc.
UPDATE public.stock_consumibles SET erp_codigo = 10002608, erp_factor = 1 WHERE nombre = 'Asa color negra (rollo) D-Pack' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10000945, erp_factor = 1 WHERE nombre = 'Banda Aldi Sur - NATUR Lieblinge' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000662, erp_factor = 0.001 WHERE nombre = 'Banda EDEKA GUT & GUNSTING' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10000595, erp_factor = 1 WHERE nombre = 'Banda GENERICA - AZUL CLARO' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000597, erp_factor = 1 WHERE nombre = 'Banda GENERICA - BLANCA NEUTRA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000421, erp_factor = 1 WHERE nombre = 'Banda HACENDADO 3 Kg. MESA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003713, erp_factor = 1 WHERE nombre = 'Banda HACENDADO 3 Kg. ZUMO' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000422, erp_factor = 0.001 WHERE nombre = 'Banda HACENDADO 5 Kg. MESA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003716, erp_factor = 1 WHERE nombre = 'Banda HACENDADO 5 Kg. ZUMO' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10000672, erp_factor = 1 WHERE nombre = 'Banda HG Azul' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10000672, erp_factor = 1 WHERE nombre = 'Banda HG Negra' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000480, erp_factor = 0.001 WHERE nombre = 'Banda LASARTE "6 KG."' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000017, erp_factor = 1 WHERE nombre = 'Banda LASARTE "ANCHAS 120"' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000537, erp_factor = 1 WHERE nombre = 'Banda LASARTE "ESPECIALES"' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000420, erp_factor = 1 WHERE nombre = 'Banda LASARTE "MANDARINAS"' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000604, erp_factor = 0.001 WHERE nombre = 'Banda MI PRIMA LA FEA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000663, erp_factor = 0.001 WHERE nombre = 'Banda NETTO' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003630, erp_factor = 1 WHERE nombre = 'Banda ORANGE LADY' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000654, erp_factor = 1 WHERE nombre = 'Banda Riesen 2 Kg (Herztucke)' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10001896, erp_factor = 1 WHERE nombre = 'Cubre CATARINA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000599, erp_factor = 1 WHERE nombre = 'Cubre CITRIANA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10002152, erp_factor = 1 WHERE nombre = 'Cubre GENERICO "PITUFOS"' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000072, erp_factor = 0.001 WHERE nombre = 'Cubre JUARRANZ' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000072, erp_factor = 0.001 WHERE nombre = 'Cubres Juarranz' AND almacen = 'exterior';
UPDATE public.stock_consumibles SET erp_codigo = 100000071, erp_factor = 0.001 WHERE nombre = 'Cubre LASARTE "PITUFOS"' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000071, erp_factor = 0.001 WHERE nombre = 'Cubre LASARTE BLOOD ORANGES' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000071, erp_factor = 0.001 WHERE nombre = 'Cubre LASARTE ESPECIALES' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000071, erp_factor = 0.001 WHERE nombre = 'Cubre LASARTE PORTUGAL' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000603, erp_factor = 1 WHERE nombre = 'Box IFCO Tipo MAGNUM' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10001390, erp_factor = 1 WHERE nombre = 'Caja cartón 08 Kg. NEGRA GENÉRICA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000491, erp_factor = 1 WHERE nombre = 'Caja cartón 12 Kg. LASARTE TAPAS' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10000079, erp_factor = 1 WHERE nombre = 'Caja cartón 15 Kg. GENERICA NEGRA (COLUMNA)' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10001008, erp_factor = 1 WHERE nombre = 'Caja cartón 15 Kg. LASARTE' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10001008, erp_factor = 1 WHERE nombre = 'Caja cartón 15 Kg. LASARTE' AND almacen = 'exterior';
UPDATE public.stock_consumibles SET erp_codigo = 100000691, erp_factor = 1 WHERE nombre = 'Caja cartón 15 Kg. MPF' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000458, erp_factor = 1 WHERE nombre = 'Caja cartón 16 Kg. LASARTE ESPECIALES' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10000069, erp_factor = 1 WHERE nombre = 'Caja cartón 20 Kg. GENERICA NEGRA COLUMNA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003546, erp_factor = 1 WHERE nombre = 'Caja cartón 20 Kg. LASARTE PLAFORM' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003546, erp_factor = 1 WHERE nombre = 'Caja cartón 20 Kg. LASARTE PLAFORM' AND almacen = 'exterior';
UPDATE public.stock_consumibles SET erp_codigo = 10002575, erp_factor = 1 WHERE nombre = 'Caja IFCO G410 BLACK' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10001164, erp_factor = 1 WHERE nombre = 'Caja madera 10 Kg. JUARRANZ' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000644, erp_factor = 1 WHERE nombre = 'Caja madera 10 Kg. JUARRANZ PINO' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003882, erp_factor = 1 WHERE nombre = 'Caja madera 10 Kg. LASARTE *44' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10002747, erp_factor = 1 WHERE nombre = 'Caja madera 10 Kg. LASARTE BLOOD ORANGE' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10000583, erp_factor = 1 WHERE nombre = 'Caja madera 10 Kg. LASARTE PREMIUM' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000500, erp_factor = 1 WHERE nombre = 'Caja madera 11 Kg. BELLE ANDALOUSE' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10001643, erp_factor = 1 WHERE nombre = 'Caja madera 15 Kg. JUARRANZ *44' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10000721, erp_factor = 1 WHERE nombre = 'Caja madera 15 Kg. LASARTE *44' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10001879, erp_factor = 1 WHERE nombre = 'Caja madera 15 Kg. LASARTE BLOOD ORANGE *44' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003727, erp_factor = 1 WHERE nombre = 'Caja plástico LOGIFRUIT 618' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10002155, erp_factor = 1 WHERE nombre = 'Caja plástico reutilizable INSERPLASA *19' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000409, erp_factor = 1 WHERE nombre = 'Caja plástico reutilizable INSERPLASA *19 MPF' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003834, erp_factor = 1 WHERE nombre = 'Caja plástico reutilizable INSERPLASA *26' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000425, erp_factor = 1 WHERE nombre = 'Caja plástico reutilizable INSERPLASA *26 MPF' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000398, erp_factor = 1 WHERE nombre = 'Corbata (ETIQUETA TIPO C2C) DESSERT 1,5' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000621, erp_factor = 0.001 WHERE nombre = 'Corbata (ETIQUETA TIPO C2C) GENERICA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003714, erp_factor = 1 WHERE nombre = 'Etiquetas Adhesivas 8 x 5,5 cm BLANCAS (MERCADONA)' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003735, erp_factor = 1 WHERE nombre = 'Etiquetas cartón Pre-Corte 4,3 x 19 cm (IFCO)' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000297, erp_factor = 0.001 WHERE nombre = 'Etiquetas cartón Pre-Corte 5 x 14,5 cm (MERCADONA)' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003463, erp_factor = 1 WHERE nombre = 'Fleje COBRE SELLADO C2C' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10000723, erp_factor = 1 WHERE nombre = 'Fleje NEGRO' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000003, erp_factor = 1 WHERE nombre = 'Gas Frutil para desverdizado' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000002, erp_factor = 1 WHERE nombre = 'Gasoil rojo para quemadores' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000050, erp_factor = 1 WHERE nombre = 'Grapas pistolas 80/4' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10002734, erp_factor = 1 WHERE nombre = 'Malla NEGRA C2C' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000596, erp_factor = 0.001 WHERE nombre = 'Malla ROJA C2C' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000650, erp_factor = 1 WHERE nombre = 'Malla ROJA MDNA. 3 Kg (es la malla normal)' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000415, erp_factor = 1 WHERE nombre = 'Malla ROJA MDNA. 5 Kg' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003718, erp_factor = 1 WHERE nombre = 'Malla ROJA MDNA. EXTRUSIONADA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10002196, erp_factor = 1 WHERE nombre = 'Palet ESPIGA 120 X 100' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000040, erp_factor = 1 WHERE nombre = 'Palet EXPORTACIÓN 120 X 90 COENCA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000038, erp_factor = 1 WHERE nombre = 'Palet FRUTERO 120 X 100' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000624, erp_factor = 1 WHERE nombre = 'Palet IFCO NESTOR' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003728, erp_factor = 1 WHERE nombre = 'Palet LOGIFRUIT 81' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000294, erp_factor = 1 WHERE nombre = 'Palet LPR Rojo 120 x 80' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000039, erp_factor = 1 WHERE nombre = 'Palet MERCADO NACIONAL 120 X 103' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000600, erp_factor = 1 WHERE nombre = 'Papel de seda GUSTAVO PREMIUM' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000606, erp_factor = 1 WHERE nombre = 'Papel de seda IMPRESIÓN NAVIDAD' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003157, erp_factor = 1 WHERE nombre = 'Papel de seda LUNARES (Flamenco)' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10002380, erp_factor = 1 WHERE nombre = 'Papel de seda MI PRIMA LA FEA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003569, erp_factor = 1 WHERE nombre = 'Papel de seda OTELLO' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000006, erp_factor = 1 WHERE nombre = 'Post cosecha ANTIESPUMANTE' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000594, erp_factor = 1 WHERE nombre = 'Post cosecha CERA IMAD - 2' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10001928, erp_factor = 1 WHERE nombre = 'Post cosecha CITROCIDE PLUS' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003836, erp_factor = 1 WHERE nombre = 'Post cosecha CITROPROTEC PLUS' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003930, erp_factor = 1 WHERE nombre = 'Post cosecha FORTISOL ADVANCE' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003573, erp_factor = 1 WHERE nombre = 'Post cosecha FUNG CID GRAS' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003165, erp_factor = 1 WHERE nombre = 'Post cosecha IMACIDE 7,5 LS' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000646, erp_factor = 1 WHERE nombre = 'Stiker AMETLLER Blanco' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000645, erp_factor = 1 WHERE nombre = 'Stiker AMETLLER Negro' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000601, erp_factor = 0.001 WHERE nombre = 'Stiker GUSTAVO PREMIUM' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000027, erp_factor = 1 WHERE nombre = 'Stiker JUARRANZ' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000026, erp_factor = 1 WHERE nombre = 'Stiker LASARTE OVALO "ESPECIALES"' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000411, erp_factor = 1 WHERE nombre = 'Stiker MI PRIMA LA FEA' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000646, erp_factor = 1 WHERE nombre = 'Stiker TARONJA BLANCO' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 100000645, erp_factor = 1 WHERE nombre = 'Stiker TARONJA NEGRO' AND almacen = 'central';
UPDATE public.stock_consumibles SET erp_codigo = 10003085, erp_factor = 1 WHERE nombre = 'VIRUTA DE CHOPO' AND almacen = 'central';
